version: "3.8"

services:

  app:
    build: fastapi/
    container_name: app
    ports:
      - 80:80

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - app
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    user: "472"
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboard1.json:/etc/grafana/provisioning/dashboards/dashboard1.json
    env_file:
      - ./grafana/password.env
